added osuosl apt repo and tests
osuosl-cookbooks/apt-osuosl pull request #1
Opened 2020-01-31 00:31 UTC by daviddjh

2020-01-31 17:27 UTC, ramereth commented
![](https://github.trello.services/images/mini-trello-icon.png) [apt-osuosl cookbook](https://trello.com/c/huS6Lutr/1572-apt-osuosl-cookbook)

2020-01-31 19:32 UTC, ramereth requested changes
Please so add ChefSpec tests for the default recipe.

2020-01-31 19:32 UTC, ramereth commented on recipes/default.rb
> +  components ['main']
```suggestion
  components %w(main)
```

2020-01-31 19:32 UTC, ramereth commented on recipes/default.rb
> +  action :add
This is the default action, please remove.

2020-01-31 19:32 UTC, ramereth commented on recipes/default.rb
> +  uri 'http://ftp.osuosl.org/pub/osl/repos/apt/'
```suggestion
  uri 'https://ftp.osuosl.org/pub/osl/repos/apt/'
```

2020-01-31 19:32 UTC, ramereth commented on recipes/default.rb
> +  key 'http://ftp.osuosl.org/pub/osl/repos/apt/repo.gpg'
```suggestion
  key 'https://ftp.osuosl.org/pub/osl/repos/apt/repo.gpg'
```

2020-02-05 17:06 UTC, ramereth requested changes
Please do a major bump by doing ``!bump major``. You will have to manually create a PR in chef-repo adding this to any environment that needs it (likely only the workstation env).

2020-02-05 17:06 UTC, ramereth approved these changes

2020-02-05 20:14 UTC, daviddjh commented
!bump major

2020-02-05 20:15 UTC, merged

2020-02-05 20:15 UTC, osuosl-manatee commented
Jenkins has merged this PR into `master` and has automatically performed a major-level version bump to v1.0.0.  Have a nice day!